name: Feature Request
description: Suggest an idea for Quests
labels: ['enhancement', 'status: needs investigating']
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, please make sure you are on the latest version of Quests.
  - type: textarea
    attributes:
      label: Reason for Addition
      description: |
        Explain your rationale for coming up with this idea.
        Your answer may describe a problem you're having, or any context for this request.
        This field is not required.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description of Feature
      description: Discuss what you would like added to Quests. Please keep your description clear and concise.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Discuss any other solutions you have tried to achieve what you wanted.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Quests
          required: true
        - label: I am certain this issue is unique and a similar issue is not currently open
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        This field is not required.
    validations:
      required: false
